# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient


def test_recordingSuite1():
    client = WindmillTestClient(__name__)

    client.open(url=u'/admin/')
    client.waits.forPageLoad(timeout=u'8000')
    client.type(text=u'admin', id=u'id_username')
    client.type(text=u'admin', id=u'id_password')
    client.click(value=u'Log in')
    client.waits.forPageLoad(timeout=u'20000')
    client.open(url=u'/')
    client.waits.forPageLoad(timeout=u'8000')
    client.waits.forElement(link=u'Edit (admin)', timeout=u'8000')
    client.click(link=u'Edit (admin)')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(timeout=u'8000', name=u'_save')
    client.click(name=u'_save')
    client.waits.forPageLoad(timeout=u'20000')
    client.open(url=u'/admin/logout/')
    client.waits.forPageLoad(timeout=u'8000')


def test_recordingSuite0():
    client = WindmillTestClient(__name__)

    client.open(url=u'/')
    client.waits.forPageLoad(timeout=u'8000')
    client.click(link=u'Login')
    client.waits.forPageLoad(timeout=u'20000')
    client.type(text=u'admin', id=u'id_username')
    client.type(text=u'admin', id=u'id_password')
    client.click(value=u'login')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[1]/td[1]/textarea[@id='id_bio']", timeout=u'8000')
    client.click(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[1]/td[1]/textarea[@id='id_bio']")
    client.click(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[1]/td[2]/textarea[@id='id_other_contacts']")
    client.click(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[2]/td[1]/input[@id='id_birth_date']")
    client.click(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[3]/td[1]/input[@id='id_surname']")
    client.click(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[4]/td[1]/input[@id='id_name']")
    client.click(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[2]/td[2]/input[@id='id_skype']")
    client.click(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[3]/td[2]/input[@id='id_jabber']")
    client.click(xpath=u"/html/body/form[@id='add_person']"
    "/table/tbody/tr[4]/td[2]/input[@id='id_email']")
